### ISSUE TITLE
The lesson needs a story (research-like problem)

### ISSUE THREAD

**Issue by olexandr-konovalov** [carpentries-incubator/sage-lesson#2]
To start with, I suggest to pick up some research-like problem, around which the lesson could centred.

We may look at some other Software Carpentry lessons at http://software-carpentry.org/lessons/ to see some examples of this approach. The GAP lesson (http://alex-konovalov.github.io/gap-lesson/) also followed this practice and used a "toy problem" of calculating the average order of an element of a group. It assumed that the learner is familiar with the group theory course at least at the undergraduate level, and walked the learner from exploring properties of groups and their elements interactively using the command line and writing simple scripts to organising code into modular programs, improving implementations and checking them with regression tests and searching in the small group library for interesting examples of groups, exposing thus a diverse variety of techniques.

If you have a suggestion for a problem or several problems which may be put into the "lesson story", please leave your comments under this issue.

**Comment by defeo** [comment]
Most likely this is too advanced, but some ideas might be taken from this tutorial I gave on linear algebra, lattices, and crypto: http://defeo.lu/sage-lattices-EJCIM/

Problem with Sage is: any story we may choose to pick will never cover the whole breadth of Sage. So we may ask ourselves first: what parts of Sage do we want to show?

**Comment by olexandr-konovalov** [comment]
@defeo thanks. That's true (about breadth), and we were in the same situation with GAP.

In principle, there may be more than one lesson, e.g. "sage-novice", "sage-advanced", "sage-some-special-topic" etc., so we need to define the audience and level of skills of the learner to whom the lesson is addressed, and proceed from there. 

What we probably want now is "sage-novice", addressed to master and postgraduate levels, assuming little or no programming skills and knowledge of the theoretical background at least at the undergraduate level. It is OK to show part of the system, but it's important to give an idea how to find further information and move on.

**Comment by drvinceknight** [comment]
What is the audience?

Would something along these lines be applicable? Using Sage to investigate a simple number theory idea: http://vknight.org/unpeudemath/code/2014/11/22/on-divisibility-by-11

Might be too simple?

**Comment by dimpase** [comment]
IMHO one needs an example to illustrate more of Sage than can be done in straight Python.

**Comment by drvinceknight** [comment]
> IMHO one needs an example to illustrate more of Sage than can be done in straight Python.

Absolutely, my example there is very basic, but perhaps something a long those lines? Some sort of conjecture that needs to be modified after using Sage to carry out experiments? I would still suggest something simple and _almost_ intuitive.

**Comment by olexandr-konovalov** [comment]
@drvinceknight thanks - your example looks to me a good starting point. My concern is maybe not that it is too simple, but that the answer (the rule of divisibility by 11) may be known in advance. If we can pick up some open number-theoretical conjecture and will try to check it as far as possible, that might fare better, and ideally expose some Sage functionality that is not available in plain Python. The audience are Sage novices who may or may not know Python already, so that will make it interesting for both.

**Comment by drvinceknight** [comment]
That sounds like a great idea. :) :+1: 

Could we do something "famous" perhaps? Would Goldbach be a possibility perhaps?

**Comment by olexandr-konovalov** [comment]
What may be nice about number-theoretical conjectures is that they are formulated in a simple and understandable way, and one could lead the learner through exploring properties of objects and writing simple scripts quite easily. Having, as @drvinceknight says, a "simple and almost intuitive" problem is good to allow the learner to concentrate on the primary goal - getting the hands-on introduction to SageMath. And then we can go further, explaining that to push feasibility bounds of calculation further one need to use specialised Sage implementations, use theory to improve the strategy, etc.

One of the examples that I've used in the past to demonstrate distributed calculations in GAP was based on 1919 conjecture by Pólya:
- For an integer _n_, the **Liouville's function** of _n_ is (-1)^_r(n)_,  where _r(n)_ is the number of prime factors of _n_, counted according to their multiplicity, with _r(1)_=0.
- The **summatory Liouville's function** _L(x)_ is the sum of values of _LiouvilleFunction(n)_ for all _n_ from 1 to _x_
- Pólya (1919) conjectured that _L(x)_<=0 for all _x_ >=2
- Haselgrove (1958) proved that this conjecture is false and there are infinitely many integers _x_ with _L(x)_>0, but he neither presented such _x_ nor gave an upper bound for the minimal _x_ with _L(x)_>0
- A computer-aided search by R. Sherman Lehman [On Liouville's Function, Math. of Computation, 1960] found the counterexample: _L_(906180359)=+1, without claiming its minimality.  It was performed on IBM 704 at UC Berkley and used caching some data on a magnetic tape
- Only 20 years later the smallest counterexample has been discovered by Tanaka: _n_ = 906150257 [A Numerical Investigation on Cumulative Sum of the Liouville Function, Tokyo J. Math., 1980]. In fact, Pólya conjecture fails for most numbers between 906150257 and 906488079, reaching 829 at _n_ = 906316571.

We may set up the goal of verifying Tanaka's experiment, or even further, find out what happens after that peak region - when the values of _L(x)_ will be positive next time after they became negative. We may also use this to show to build plots in Sage. This should be feasible to compute - in my talk, I was starting a farm of 30+ GAP SCSCP servers and by the end of the 20-minute talk Tanaka's counterexample was verified.

And yes, while I was writing this, another comment from @drvinceknight arrived - Goldbach's was definitely on my mind too.

**Comment by dimpase** [comment]
I'd go even further, I'd start off by building a graph from a group and
then compute its Lovasz theta (a graph parameter that is sandwiched between
two parameters which are hard to compute: the chromatic number and the
clique number), something that needs a  semi-definite optimisation solver.
(all of this is in Sage, none of it is in a proper subset of Sage :-))

**Comment by olexandr-konovalov** [comment]
@dimpase thanks. Is there a Sage worksheet somewhere to look at these calculations?

**Comment by dimpase** [comment]
at least once you get Sage graph, it's one line.

```
 sage: p=graphs.HoffmanSingletonGraph().complement()
 sage: p.lovasz_theta()
 3.3333333
```

**Comment by olexandr-konovalov** [comment]
@gvwilson is putting together an outline of a new introduction to Python for complete novices here: https://github.com/swcarpentry/python-novice-gapminder/blob/gh-pages/index.md. It may be useful to have a look, and we may want to follow this top-down approach and discuss and write down an outline before writing up the complete lesson.

**Comment by gvwilson** [comment]
This outline uses a modified version of the "Understanding by Design" 
process:
1. Assumptions about audience, time, etc.  (Current draft also includes 
   some conclusions/decisions in this section - that should be refactored.)
2. Desired results: overall goals, summative assessments at half-day 
   granularity, what learners will be able to do, what learners will know.
3. Learning plan: each episode has a heading that summarizes what will 
   be covered, then estimates time that will be spent on teaching and on 
   exercises, and the exercises (formative assessents) are given bullet points.

It _looks_ like a waterfall process, but in practice I did this:
1. Draft the assumptions.
2. Do one bullet point for each of several learning milestones.
3. Draft the desired results.
4. Update the learning milestones (still as just one bullet point each, 
   no time estimates or exercises).
5. Get feedback.
6. Do a full pass to add time estimates and exercises and flesh out the 
   assumptions.
7. Ask for more feedback.

At the start of #7 above, the lesson needed 8.5 hours (vs. a budget of 
6.5), so iterating on feedback mostly meant cutting things. NumPy went, 
as did everything to do with running scripts from the command line and a 
bunch of other topics that are useful and important, but not _as_ 
important as what's there.  This was also the point at which I settled 
on using the Jupyter Notebook (I'd decided on the Gapminder data set at 
the outset to be consistent with Data Carpentry).

On 2016-02-10 9:51 AM, Alexander Konovalov wrote:

> @gvwilson https://github.com/gvwilson is putting together an outline 
> of a new introduction to Python for complete novices here: 
> https://github.com/swcarpentry/python-novice-gapminder/blob/gh-pages/index.md. 
> It may be useful to have a look, and we may want to follow this 
> top-down approach and discuss and write down an outline before writing 
> up the complete lesson.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/alex-konovalov/sage-lesson/issues/2#issuecomment-182405528.

## 

Dr Greg Wilson
Director of Instructor Training
Software Carpentry Foundation

**Comment by olexandr-konovalov** [comment]
@gvwilson thank you - that's very helpful. I will add an outline file to the repository and with try to write some details next week.

**Comment by olexandr-konovalov** [comment]
FYI: @gvwilson wrote a new blog post on collaborative lesson design here:http://software-carpentry.org/blog/2016/02/designing-lessons-collaboratively.html. Please have a look!

**Comment by drvinceknight** [comment]
I think this point from there is crucial:

> The next step is to figure out how to go about writing the lesson. Should one or two people assemble a first draft for others to critique? Or should we start by crowd-sourcing the creation of the exercises (which I think will parallelize better)? And if we do the latter, should we ask instructor trainees who already speak Python to propose exercises as part of their training? Comments would be greatly appreciated.

I was purposefully not adding to the discussion as I didn't want too many voices impeding progress. I'm not sure what the best way to proceed is.

As far as platform is concerned, I would have thought we would use SMC. What does everyone else think?

**Comment by olexandr-konovalov** [comment]
We should have a separate issue to discuss the question about the platform.

SMC (SageMathCloud, https://cloud.sagemath.com/) is good to ensure that all users have same experience independently on their operating system. On the other hand, this makes teaching very dependent on the network connection (workshop for 40 people in the same room will require extra care). Also, it's good if the workshop gives a hands-on tutorial after which learners are able to continuing on their own machines (as a usual condition of the workshop is to bring your own laptop). With a cloud based solution this may not be the case. So each choice has its own benefits and downsides.

**Comment by drvinceknight** [comment]
> With a cloud based solution this may not be the case. So each choice has its own benefits and downsides.

Although in this case learners are able to continue "in the cloud". Opening a second issue is a good idea: connectivity is an important issue...

**Comment by slel** [comment]
SageMathCloud is a great platform for such a training (given a reliable internet connection).
It allows to dive right into the subject matter, bypassing or postponing installation questions.

**Comment by alex-konovalov** [comment]
@drvinceknight wrote:

> Would something along these lines be applicable? Using Sage to investigate a simple number theory idea: http://vknight.org/unpeudemath/code/2014/11/22/on-divisibility-by-11/

The link does not work any more - do you have new URL? Thanks

**Comment by olexandr-konovalov** [comment]
The story we picked up is exploring the mathematical underpinnings of icosahedral virus structure, suggested by @ppd22. You can see an overview in https://github.com/alex-konovalov/sage-lesson/blob/gh-pages/index.md.
